apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-app-scale-development
  annotations:
    argo.octopus.com/project: "asd"
    argo.octopus.com/environment: "development"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: development
  sources:
    - repoURL: https://github.com/ATGardner/git-source.git
      targetRevision: main
      path: base-demo-app/development
    - repoURL: https://github.com/ATGardner/git-source.git
      targetRevision: main
      path: base-demo-app/development-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
