# https://github.com/grafana/docker-otel-lgtm/blob/main/k8s/lgtm.yaml
apiVersion: v1
kind: Service
metadata:
  name: lgtm
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otel-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: pyro-http
      protocol: TCP
      port: 9097
      targetPort: 9097
