apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-qa
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: simple
  labels:
    env: qa
spec:
  project: default
  source:
    repoURL: https://github.com/codefresh-io/argo-platform.git
    targetRevision: test-ignore
    path: simple-apps/qa
  destination:
    name: in-cluster
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
    - ServerSideApply=true
    - RespectIgnoreDifferences=false
