apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    codefresh.io/env: production
    codefresh.io/gitops-operator-version: 0.7.7
    codefresh.io/product: loans
    codefresh.io/promotion-flow: complex
    codefresh.io/promotion-stage: on-start-release-step
    codefresh.io/release: 6829f42cd655007e66667a51
    codefresh.io/release-name: 148e4a78b
    codefresh.io/workflow-origin: promotion
  generateName: test-namespace-
spec:
  arguments:
    parameters:
      - name: RELEASE_ID
        value: 6829f42cd655007e66667a51
      - name: PRODUCT_NAME
        value: loans
      - name: VERSION
        value: 1.2.4
      - name: COMMIT_SHA
        value: 148e4a78b9fe652010a74f15588781f9b9dabacb
      - name: PROMOTION_FLOW_NAME
        value: complex
      - name: RELEASE_URL
        value: https://g.codefresh.io/2.0/products/loans/releases/6829f42cd655007e66667a51?activeAccountId=5f6a52f5f0f4b845ef443a58
      - name: ENVIRONMENT_NAME
        value: production
  entrypoint: echo
  templates:
  - inputs:
      parameters:
      - name: RELEASE_ID
      - name: PRODUCT_NAME
      - name: COMMIT_SHA
      - name: PROMOTION_FLOW_NAME
      - name: RELEASE_URL
    name: echo
    script:
      command:
      - sh
      image: alpine:3.21
      source: |
        sleep 5
        echo "on-start-release for release {{ inputs.parameters.RELEASE_ID }}"
        echo "productName: \"{{ inputs.parameters.PRODUCT_NAME }}\", commitSha: {{ inputs.parameters.COMMIT_SHA }}, promotionFlowName: \"{{ inputs.parameters.PROMOTION_FLOW_NAME }}\""
        echo "releaseUrl: {{ inputs.parameters.RELEASE_URL }}"
