apiVersion: csdp.codefresh.io/v1
kind: ApplicationConfiguration
metadata:
  name: base-helm
spec:
  applicationSourceSelector:
    matchLabels:
      app: helm-app
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: appVersion
  promotion:
    chart.yaml:
      jsonPaths:
      - $.appVersion
      - $.version
      - $.dependencies
    values.yaml:
      jsonPaths:
      - $..image
    requirements.yaml:
      jsonPaths:
      - "$.dependencies"
