apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loans-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: loans
  labels:
    app: loans
    env: qa
spec:
  project: default
  source:
    repoURL: https://github.com/noam-codefresh/git-source.git
    targetRevision: qa
    path: loans
  destination:
    name: in-cluster
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
