apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loans-production-east
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    app: loans
    codefresh.io/product: loans
    env: production
spec:
  project: default
  source:
    repoURL: https://github.com/noam-codefresh/git-source.git
    targetRevision: production-east
    path: loans
  destination:
    name: noam
    namespace: production-east
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
