apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loans-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    app: loans
    acodefresh.io/product: loans
    env: qa
    codefresh.io/product: loans
spec:
  project: default
  source:
    path: loans-apps/qa
    repoURL: https://github.com/noam-codefresh/git-source.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
