apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loans-staging-5
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: loans
  labels:
    env: staging
spec:
  project: default
  source:
    repoURL: https://github.com/ATGardner/git-source.git
    targetRevision: main
    path: loans-apps/staging-5
  destination:
    name: in-cluster
    namespace: staging-5
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
