apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: calendar-8fc3ae53-8b5e-441c-b1b1-5662fef62980
      eventName: calendar-8fc3ae53-8b5e-441c-b1b1-5662fef62980
      eventSourceName: sensor-nw
    - name: github-60a67dda-8c57-45fc-9581-afa0851d4f64
      eventName: github-60a67dda-8c57-45fc-9581-afa0851d4f64
      eventSourceName: sensor
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - issue_comment
            type: string
  triggers:
    - template:
        name: trigger
        conditions: >-
          calendar-8fc3ae53-8b5e-441c-b1b1-5662fef62980 ||
          github-60a67dda-8c57-45fc-9581-afa0851d4f64
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: sensor-trigger-
              spec:
                arguments:
                  parameters:
                    - name: APP_NAMESPACE
                      value: some-namespace
                    - name: APP_NAME
                      value: some-name
                workflowTemplateRef:
                  name: pipeline-wf
          parameters: []
