apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sensor
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-60a67dda-8c57-45fc-9581-afa0851d4f64:
      events:
        - issue_comment
      repositories:
        - owner: ATGardner
          names:
            - git-source
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/runtime/sensor/github-60a67dda-8c57-45fc-9581-afa0851d4f64
        url: https://noam-ap.ngrok.io
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
