apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sensor-nw
spec:
  eventBusName: codefresh-eventbus
  template:
    serviceAccountName: argo-server
  calendar:
    calendar-8fc3ae53-8b5e-441c-b1b1-5662fef62980:
      interval: 4h
