apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deployed-promotion-tmpl
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: POST_SYNC_WORKFLOW
    - name: ARGS
  templates:
  - name: main
    steps:
    - - name: post-sync
        when: "{{ workflow.parameters.POST_SYNC_WORKFLOW }} != ''"
        arguments:
          parameters:
          - name: TEMPLATE_NAME
            value: "{{ workflow.parameters.POST_SYNC_WORKFLOW }}"
          - name: ARGS
            value: "{{ workflow.paremeters.ARGS }}"
        templateRef:
          template: submit
          name: submit-workflow
