apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-action
  labels:
    codefresh.io/promotion: 'true'
spec:
  arguments:
    parameters:
    - name: sha
  entrypoint: echo
  templates:
  - name: echo
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "post action app {{ workflow.parameters.sha }}"
