apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: post-action-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: post-action-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: post-action-cr
subjects:
- kind: ServiceAccount
  name: post-action-sa
  namespace: default

---

apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: post-action-sa
