apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action
  labels:
    codefresh.io/promotion: 'true'
spec:
  arguments:
    parameters:
    - name: APP_NAME
  entrypoint: echo
  templates:
  - name: echo
    inputs:
      parameters:
      - name: APP_NAME
    outputs:
      parameters:
      - name: RESULT
        valueFrom:
          path: /tmp/result
        globalName: RESULT
    script:
      image: alpine
      env:
      - name: APP_NAME
        value: "{{ inputs.paramaters.APP_NAME }}"
      command:
      - sh
      source: |
        echo "pre action ${APP_NAME}" > /tmp/result
        cat /tmp/result        
