apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action
  labels:
    codefresh.io/promotion: 'true'
spec:
  arguments:
    parameters:
    - name: APP_NAME
  entrypoint: echo
  templates:
  - name: echo
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "pre action {{ workflow.parameters.APP_NAME }}"
