apiVersion: v1
kind: ServiceAccount
metadata:
  name: promotion-templates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promotion-templates
  annotations:
    argo-hub/version: '0.0.1'
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get
  - list
  - patch
  - watch 
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtasksets
  verbs:
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflowtasksets/status
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promotion-templates
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: promotion-templates
subjects:
  - kind: ServiceAccount
    namespace: runtime
    name: promotion-templates
