apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sleep
spec:
  serviceAccountName: pre-action-sa
  entrypoint: sleep
  templates:
  - name: sleep
    script:
      image: quay.io/noam_codefresh/curl-base:8.9.1
      command:
      - sh
      source: |
        echo "before"
        sleep 5
        echo "after"
 