apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sleep
spec:
  entrypoint: sleep
  templates:
  - name: sleep
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "before"
        sleep 60
        echo "after"
 