apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sleep
  annotations:
    codefresh.io/workflow-origin: promotion
    codefresh.io/promotion-stage: pre-action
    version: 0.0.1
    description: 'a 1-step pre-action that sleeps for 5s'
spec:
  serviceAccountName: pre-action-sa
  entrypoint: sleep
  templates:
  - name: sleep
    script:
      image: alpine:3.20
      command:
      - sh
      source: |
        echo "before"
        sleep 5
        echo "after"
 