apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: submit-workflow
spec:
  arguments:
    parameters:
    - name: TEMPLATE_NAME
    - name: ARGS
  entrypoint: submit
  templates:
  - name: submit
    serviceAccountName: argo-workflow-controller
    inputs:
      parameters:
      - name: TEMPLATE_NAME
      - name: ARGS
    outputs:
      parameters:
      - name: output
        valueFrom:
          path: /output.json
    script:
      name: main
      image: quay.io/codefreshplugins/argo-hub-argo-workflows-argo-workflow-cli:0.0.4-main
      command:
      - sh
      source: |
        echo {{ inputs.parameters.ARGS }} > params.json
        echo $(argo submit \
          --from wftmpl/{{ inputs.parameters.TEMPLATE_NAME }} \
          --parameter-file params.json \
          --labels codefresh.io/submit-wf-parent-uid={{ workflow.uid }} \
          --output=json) > output.json
