apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  serviceAccountName: promotion-templates
  entrypoint: main-tmpl
  arguments:
    parameters:
    - name: PRE_ACTION
      value: ""
    - name: ACTION
      value: ""
  templates:
  - name: main-tmpl
    inputs:
      parameters:
      - name: PRE_ACTION
        value: "{{workflow.parameters.PRE_ACTION}}"
      - name: ACTION
        value: "{{workflow.parameters.ACTION}}"
    dag:
      tasks:
      - name: pre-run
        template: action-dag-tmpl
        arguments:
          parameters:
          - name: PRE_ACTION
            value: "{{inputs.parameters.PRE_ACTION}}"
          - name: ACTION
            value: "{{inputs.parameters.ACTION}}"

      - name: post-action
        depends: "pre-run"
        template: echo-tmpl
        arguments:
          artifacts:
          - name: FILE
            raw:
              data: "{{tasks.pre-run.outputs.parameters.RESULT}}"

  - name: action-dag-tmpl
    inputs:
      parameters:
      - name: PRE_ACTION
      - name: ACTION
    outputs:
      parameters:
      - name: RESULT
        valueFrom:
          expression: "inputs.parameters.ACTION == '' ? tasks['pre-action'].outputs.parameters.RESULT : tasks.action.outputs.parameters.RESULT"
    dag:
      tasks:
      - name: pre-action
        when: "{{= inputs.parameters.PRE_ACTION != ''}}"
        template: echo-tmpl
        arguments:
          artifacts:
          - name: FILE
            raw:
              data: |
                file from pre-action {{inputs.parameters.PRE_ACTION}}

      - name: action
        when: "{{= inputs.parameters.ACTION != ''}}"
        depends: "pre-action"
        template: echo-tmpl
        arguments:
          artifacts:
          - name: FILE
            raw:
              data: |
                file from action {{inputs.parameters.ACTION}}
      
      - name: fail
        depends: "pre-action.Skipped && action.Skipped"
        template: fail-tmpl

      - name: suspend
        depends: "(pre-action.Succeeded && !action.Failed) || action.Succeeded"
        template: suspend-tmpl

  - name: echo-tmpl
    inputs:
      artifacts:
      - name: FILE
        path: /tmp/file
    outputs:
      parameters:
      - name: RESULT
        valueFrom:
          path: /tmp/result
    script:
      name: echo-script
      image: alpine
      command:
      - sh
      source: |
        echo "before"
        cat /tmp/file > /tmp/result
        cat /tmp/result
        echo "after"

  - name: fail-tmpl
    container:
      image: alpine:latest
      command:
      - sh
      - -c
      args:
      - exit 1

  - name: suspend-tmpl
    suspend: {}