apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test
spec:
  serviceAccountName: promotion-templates
  entrypoint: main-tmpl
  arguments:
    parameters:
    - name: ARG
  templates:
  - name: main-tmpl
    inputs:
      parameters:
      - name: ARG
        value: "{{workflow.parameters.ARG}}"
    dag:
      tasks:
      - name: A
        template: sub-tmpl
        arguments:
          parameters:
          - name: ARG
            value: "{{inputs.parameters.ARG}}"

      - name: B
        depends: "A"
        template: echo-tmpl
        arguments:
          artifacts:
          - name: FILE
            raw:
              data: "{{tasks.A.outputs.parameters.RESULT}}"


  - name: sub-tmpl
    inputs:
      parameters:
      - name: ARG
    outputs:
      parameters:
      - name: RESULT
        valueFrom:
          expression: "inputs.parameters.ARG == 'one' ? tasks.A1.outputs.parameters.RESULT : tasks.A2.outputs.parameters.RESULT"
    dag:
      tasks:
      - name: A1
        when: "{{= inputs.parameters.ARG == 'one'}}"
        template: echo-tmpl
        arguments:
          artifacts:
          - name: FILE
            raw:
              data: |
                file from A1

      - name: A2
        when: "{{= inputs.parameters.ARG != 'one'}}"
        depends: "A1"
        template: echo-tmpl
        arguments:
          artifacts:
          - name: FILE
            raw:
              data: |
                file from A2

  - name: echo-tmpl
    inputs:
      artifacts:
      - name: FILE
        path: /tmp/file
    outputs:
      parameters:
      - name: RESULT
        valueFrom:
          path: /tmp/result
    script:
      name: echo-script
      image: alpine
      command:
      - sh
      source: |
        echo "before"
        cat /tmp/file > /tmp/result
        cat /tmp/result
        echo "after"
