apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/idan-codefresh/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
  destination:
    name: in-cluster
    namespace: idan-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
    - ServerSideApply=true
    - RespectIgnoreDifferences=false
