apiVersion: csdp.codefresh.io/v1
kind: PromotionFlow
metadata:
  name: base-flow
spec:
  triggerEnvironment: qa
  steps:

  - environment: staging
    dependsOn:
    - dev
    policy:
      # preAction, preSync and PostSync are *not* required
      # preSync is meaningless if the app is set to autoSync in argocd (will not run preSync)
      preAction: 'aaa'
      preSync: 'bbb'
      postSync: 'ccc'
      # action is a required field
      action: commit # commit|pr|none

  - environment: productiona
    dependsOn:
    - staging
    policy:
      postSync: 'notify-slack'
      action: commit # commit|pr|none
