apiVersion: csdp.codefresh.io/v1
kind: PromotionFlow
metadata:
  name: base-flow
spec:
  productSelector: loans
  triggerEnvironment: qa
  priority: 0
  steps:
  - environment: staging
    dependsOn:
    - dev
  - environment: production
    dependsOn:
    - staging
