apiVersion: csdp.codefresh.io/v1
kind: PromotionFlow
metadata:
  name: base-flow
spec:
  triggerEnvironment: dev
  # postAction: 'bbb'
  steps:

  - environment: staging
    dependsOn:
    - dev
    policy:
      # preAction, preSync and PostSync are *not* required
      # preSync is meaningless if the app is set to autoSync in argocd (will not run preSync)
      preAction: 'aaa'
      postAction: 'ccc'
      # action is a required field
      action: none # commit|pr|none

  - environment: production
    dependsOn:
    - staging
    policy:
      postAction: 'notify-slack'
      action: commit # commit|pr|none
