apiVersion: csdp.codefresh.io/v1
kind: PromotionFlow
metadata:
  name: base-flow
spec:
  triggerEnvironment: qa
  steps:
  - environment: staging
    dependsOn:
    - dev
  - environment: productiona
    dependsOn:
    - staging
