apiVersion: csdp.codefresh.io/v1
kind: PromotionFlow
metadata:
  name: base-flow
spec:
  triggerEnvironment: dev
  postTrigger: 'post-action'
  steps:

  - environment: staging
    dependsOn:
    - dev
    policy:
      # preAction and postAction are *not* required
      preAction: 'pre-action'
      postAction: 'post-action'
      # action is a required field
      action: commit # commit|pr|none

  - environment: production
    dependsOn:
    - staging
    policy:
      preAction: 'pre-action'
      postAction: 'post-action'
      action: commit # commit|pr|none
