apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: event-reporter-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: event-reporter
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
