# helm install my-kube-prometheus-stack oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack:72.5.0
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/prometheus-community/charts
    chart: kube-prometheus-stack
    targetRevision: 72.5.0 
    # helm:
    #   values: |
    #     nodeExporter:
    #       enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus # Target namespace for deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensures the target namespace is created if it doesn't exist
      - ServerSideApply=true
