apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sensor-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      controller: sensor-controller
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
