apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-production-4
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: dummy
  labels:
    env: production-internal
spec:
  project: default
  source:
    # repoURL: https://github.com/ATGardner/git-source.git
    repoURL: https://github.com/ATGardner/applications.git
    targetRevision: main
    path: dummy-apps/production-4
  destination:
    name: in-cluster
    namespace: production-4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
