apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-staging-2
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: dummy
  labels:
    env: staging
spec:
  project: default
  source:
    repoURL: https://github.com/codefresh-io/argo-platform.git
    targetRevision: test-ignore
    path: dummy-apps/staging-2
  destination:
    name: in-cluster
    namespace: staging-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
