apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-production-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    env: production
  annotations:
    codefresh.io/product: dummy
spec:
  project: default
  destination:
    name: in-cluster
    namespace: production-1
  source:
    repoURL: https://github.com/codefresh-io/argo-platform.git
    targetRevision: test-ignore
    path: dummy-apps/production-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
