apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-staging-4
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: dummy
  labels:
    env: staging-internal
spec:
  project: default
  source:
    repoURL: https://github.com/ATGardner/git-source.git
    # repoURL: https://github.com/codefresh-io/argo-platform.git
    targetRevision: main
    # targetRevision: CR-29159-fix-app-proxy-memory
    path: dummy-apps/staging-4
  destination:
    name: in-cluster
    namespace: staging-4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
