apiVersion: csdp.codefresh.io/v1
kind: ApplicationConfiguration
metadata:
  name: base-helm
spec:
  applicationSourceSelector:
    matchExpressions:
    - key: codefresh.io/product
      operator: Exists
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: appVersion
  promotion:
    Chart.yaml:
      jsonPaths:
      - $.appVersion
      - $.version
      - $.dependencies
    values.yaml:
      jsonPaths:
      - $..image
    requirements.yaml:
      jsonPaths:
      - "$.dependencies"
