apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loans-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/noam-codefresh/git-source.git
    targetRevision: test
    path: loans
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
