apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: bXl1c2VybmFtZQ== # base64 encoded value of "myusername"
  password: bXlwYXNzd29yZA== # base64 encoded value of "mypassword"
