apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-rgs-production
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: simple-rgs
  labels:
    env: production
spec:
  project: test-rgs
  source:
    repoURL: https://github.com/ATGardner/git-source.git
    targetRevision: main
    path: simple-apps/production
  destination:
    name: in-cluster
    namespace: cf-restricted
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
