apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/danielm-codefresh/canary-rollout.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: runtime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
