apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-external-egress
spec:
  # Apply this policy to all pods in the namespace
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  # Rule 1: Allow traffic to all pods in all namespaces within the cluster.
  # This covers pod-to-pod communication cluster-wide.
  - to:
    - podSelector: {}
      namespaceSelector: {}

  # Rule 2: Allow DNS requests. This is essential for resolving service names.
  # It allows traffic to pods labeled 'k8s-app: kube-dns' in the 'kube-system' namespace on port 53.
  - to:
    - namespaceSelector:
        matchLabels:
          # This label is standard for the kube-system namespace
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
