apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-forward-proxy
  labels:
    app: nginx-forward-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-forward-proxy
  template:
    metadata:
      labels:
        app: nginx-forward-proxy
    spec:
      containers:
      - name: nginx-forward-proxy
        image: quay.io/noam_codefresh/nginx-forward-proxy:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-forward-proxy-service
spec:
  type: LoadBalancer # Use NodePort or ClusterIP if you're not on a cloud provider
  selector:
    app: nginx-forward-proxy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
