loans:
  image:
    repository: quay.io/noam_codefresh/loans
    tag: v2
    pullPolicy: Always

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicaCount: 2

interest:
  image:
    repository: quay.io/noam_codefresh/interest
    tag: v2
  replicaCount: 1
