loans:
  image:
    repository: quay.io/noam_codefresh/loans
    tag: v2

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  interest:
    image:
      repository: quay.io/noam_codefresh/interest
      tag: v1

# a change in a different directory
