apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: base-flow
spec:
  triggerEnvironment: qa
  # postTrigger: 'post-action'
  steps:
  - environment: staging
    dependsOn:
    - qa
    policy:
      # preAction and postAction are *not* required
      preAction: 'pre-action'
      postAction: 'post-action'
      # action is a required field
      action: commit # commit|pr|none

  - environment: prod
    dependsOn:
    - staging
    policy:
      preAction: 'pre-action'
      postAction: 'post-action'
      action: commit # commit|pr|none
