apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: base-flow
spec:
  triggerEnvironment: qa
  postTrigger: 'post-action'
  steps:
  - environment: staging
    dependsOn:
    - qa
    policy:
      preAction: 'pre-action'
      postAction: 'post-action'
      action: commit

  - environment: prod
    dependsOn:
    - staging
    policy:
      preAction: 'pre-action'
      postAction: 'post-action'
      action: commit
