apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: loans
spec:
  applicationSourceSelector:
    matchLabels:
      codefresh.io/product: loans
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: $.version
  promotion:
    Chart.yaml:
      jsonPaths:
      - $.appVersion
      - $.version
      - $.dependencies
    values.yaml:
      jsonPaths:
      - $..image
