apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: rollout
spec:
  applicationSourceSelector:
    matchLabels:
      codefresh.io/product: rollout
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: $.version
  promotion:
    canary-rollout.yaml:
      jsonPaths:
      - $..image
