apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rel-qa
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: rel
  labels:
    env: qa
spec:
  project: default
  source:
    repoURL: https://github.com/ATGardner/git-source.git
    targetRevision: main
    path: rel-apps/qa/chart
  destination:
    name: in-cluster
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
    - ServerSideApply=true
    - RespectIgnoreDifferences=false
