apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: load-applicationset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/atgardner/git-source
      revision: HEAD
      files:
      - path: "load-apps/*.json"
  template:
    metadata:
      name: "load-{{.path.filenameNormalized}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/atgardner/git-source
        targetRevision: HEAD
        path: load-apps/app
      destination:
        name: in-cluster
        namespace: "load-{{.path.filenameNormalized}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - PrunePropagationPolicy=foreground
        - Replace=false
        - PruneLast=false
        - Validate=true
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=false
        - ServerSideApply=true
        - RespectIgnoreDifferences=false

