loans:
  image:
    repository: quay.io/noam_codefresh/loans
    tag: v3

  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

interest:
  image:
    repository: quay.io/noam_codefresh/interest
    tag: v3

  replicaCount: 1
