apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rgs-app #
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: rgs #
  source:
    path: good-app #
    repoURL: https://github.com/ATGardner/git-source.git #
    targetRevision: HEAD #
  destination:
    name: in-cluster
    namespace: rgs-dest #
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
