apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: good-app #
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: rgs-apps #
  source:
    path: good-app #
    repoURL: https://github.com/noam-codefresh/git-source.git #
    targetRevision: HEAD #
  destination:
    name: in-cluster
    namespace: rgs-dest #
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
