apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overwrite-namespace
  namespace: runtime # <- illeagal namespace
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: rgs-test #
  source:
    repoURL: https://github.com/ATGardner/git-source.git
    targetRevision: HEAD
    path: rgs-apps/overwrite-namespace #
  destination:
    name: in-cluster
    namespace: cf-restricted #
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
