apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/ATGardner/git-source.git
    targetRevision: HEAD
    path: good-app
  destination:
    name: daniel
    namespace: from-noam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
