apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wrong-dest-ns
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: hulk-team
  source:
    repoURL: https://github.com/ATGardner/git-source.git
    targetRevision: HEAD
    path: wrong-dest-ns
  destination:
    name: in-cluster
    namespace: runtime # <-- illeagal namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - Replace=false
    - PruneLast=false
    - Validate=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
