loans:
  image:
    repository: quay.io/noam_codefresh/loans
    tag: v2
  replicaCount: 1
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
  podAnnotations:
    key: "2024-11-03T13:05:21Z"
interest:
  image:
    repository: quay.io/noam_codefresh/interest
    tag: v1
  replicaCount: 1
