loans:
  image:
    repository: quay.io/noam_codefresh/loans
    tag: v2
    pullPolicy: Always

  replicaCount: 3

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

interest:
  image:
    repository: quay.io/noam_codefresh/interest
    tag: v2

  replicaCount: 2
