loans:
  image:
    repository: quay.io/noam_codefresh/loans
    tag: v2
  replicaCount: 1
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
  podLabels:
    key: "2024-11-03T12:13:18Z"
interest:
  image:
    repository: quay.io/noam_codefresh/interest
    tag: v1
  replicaCount: 1
